/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package childrenvaccination;
import java.sql.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ZAHIR
 */
public class search extends javax.swing.JFrame {

    /**
     * Creates new form search
     */
    public search() {
        initComponents();
        Db mydb = new Db();
        try {
            Connection con = mydb.getconnection();
            String sql = "select * from child";
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            st.close();
            con.close();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_city = new javax.swing.JTextField();
        jButton_city = new javax.swing.JButton();
        jButton_vaccinenumber = new javax.swing.JButton();
        jButton_id = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_vaccinenumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("City");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 30, 20));
        jPanel1.add(jTextField_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, -1));

        jButton_city.setBackground(new java.awt.Color(51, 255, 0));
        jButton_city.setText("Search");
        jButton_city.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_cityMouseClicked(evt);
            }
        });
        jButton_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cityActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jButton_vaccinenumber.setBackground(new java.awt.Color(51, 255, 0));
        jButton_vaccinenumber.setText("Search");
        jButton_vaccinenumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_vaccinenumberMouseClicked(evt);
            }
        });
        jPanel1.add(jButton_vaccinenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jButton_id.setBackground(new java.awt.Color(51, 255, 51));
        jButton_id.setText("Search");
        jButton_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_idMouseClicked(evt);
            }
        });
        jPanel1.add(jButton_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Vaccine Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, -1));

        jTextField_vaccinenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_vaccinenumberActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_vaccinenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 50, 20));
        jPanel1.add(jTextField_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("Advance Search");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 160, 40));

        jButton1.setBackground(new java.awt.Color(255, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_vaccinenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_vaccinenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_vaccinenumberActionPerformed

    private void jButton_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_cityActionPerformed

    private void jButton_cityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_cityMouseClicked
        // TODO add your handling code here:
        String city = jTextField_city.getText();
        Db mydb = new Db();
        try {
            Connection con = mydb.getconnection();
            String sql = "select * from child where City='"+city+"'";
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            st.close();
            con.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_cityMouseClicked

    private void jButton_vaccinenumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_vaccinenumberMouseClicked
        // TODO add your handling code here:
        String vaccine = jTextField_vaccinenumber.getText();
        Db mydb = new Db();
        try {
            Connection con = mydb.getconnection();
            String sql = "select * from child where VaccineNumber='"+vaccine+"'";
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            st.close();
            con.close();
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_jButton_vaccinenumberMouseClicked

    private void jButton_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_idMouseClicked
        // TODO add your handling code here:
        String id = jTextField_id.getText();
        Db mydb = new Db();
        try {
            Connection con = mydb.getconnection();
            String sql = "select * from child where ID ='"+id+"'";
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            st.close();
            con.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_idMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showchildren.main(new String[]{});
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_city;
    private javax.swing.JButton jButton_id;
    private javax.swing.JButton jButton_vaccinenumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_city;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_vaccinenumber;
    // End of variables declaration//GEN-END:variables
}
